### ISSUE TITLE
Add a user profile page 

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#113]
WHO: Cecelia

Have profile page:

first name
last name
email
project membership
password details

**Comment by allynt** [comment]
This page already exists.  But it is viewable only by that user and the site admin (b/c it was intended to be used for the user to change their profile).  I could add a read-only version of this page w/out the password details for everyone else.

**Comment by murphysj** [comment]
No. We don't need that. Then close this.

On Wed, Aug 5, 2015 at 1:34 PM, allynt <notifications@github.com> wrote:

> This page already exists. But it is viewable only by that user and the
> site admin (b/c it was intended to be used for the user to change their
> profile). I could add a read-only version of this page w/out the password
> details for everyone else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/113#issuecomment-128122640>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
