### ISSUE TITLE
Hide or minimize properties of attributes that are customized to "not display" in the customizer

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#118]
WHO: Rocky

So they are not seen

**Comment by allynt** [comment]
Moving them to the bottom is a bad idea b/c that affects the order that the properties will be displayed in.  What about having a toggle at the top of all accordions to switch between showing all properties and showing only those properties customized to display?

**Comment by allynt** [comment]
30de500556b8a5f53554f04d1e669208500f146a greys out the header of non-displayed properties.  That's good enough.
