### ISSUE TITLE
Standardize button sizes across the application

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#134]
WHO: Sylvia

When we added a new "view" button, it is larger than others. There is no CSS controlling that. Standardize in CSS.

**Comment by allynt** [comment]
I'm not sure which buttons you're referring to?  The ones on the Project Page?  If so, shouldn't they be the size of their text (and so not the same)?

**Comment by murphysj** [comment]
I believe this was referring to the save, publish etc buttons on various
pages.

On Wed, Aug 5, 2015 at 1:27 PM, allynt <notifications@github.com> wrote:

> I'm not sure which buttons you're referring to? The ones on the Project
> Page? If so, shouldn't they be the size of their text (and so not the same)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/134#issuecomment-128119909>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
Shouldn't they be different sizes?  

"this small button" should be smaller than "this much larger button with more text"

Unless this ticket is referring to vertical height or if "save" on page x looks different than "save" on page y (I don't think either of those are true, though).

**Comment by murphysj** [comment]
You will want the same height and padding for all. Fonts should be the
save. Obviously a button with Publish will be longer than a button with
Save.
Need consistency between page x and y. This may be done now. This was
ticket was created before a lot of the standardization that was going on.

On Wed, Aug 5, 2015 at 1:51 PM, allynt <notifications@github.com> wrote:

> Shouldn't they be different sizes?
>
> "this small button" should be smaller than "this much larger button with
> more text"
>
> Unless this ticket is referring to vertical height or if "save" on page x
> looks different than "save" on page y (I don't think either of those are
> true, though).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/134#issuecomment-128128689>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
