### ISSUE TITLE
Be able to keep underscores in mindmap properties so they exist in the Questionnaire

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#145]
WHO: Anna

Anna has put underscores in here mindmap attributes. in the CIM an underscore is not part of the name and means something different. 

This is happening in Rupert Ford's old mindmap conversion code.

Allyn has already created a modified version of this code, but we need to think about how CMIP6 will work an whether dumping this convention is a good idea.

**Comment by allynt** [comment]
Rupert's old mindmap conversion code will no longer be used going forward.
