### ISSUE TITLE
Implement versioning

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#15]
WHO: NCPP, ES-DOC (Mark)

Upon "publication" version should be incremented and XML should be available to the ATOM feed.
The Questionnaire should only be able to view/edit the latest version.

**Comment by murphysj** [comment]
Is this still true? We seem to have versioning in the feed?

**Comment by allynt** [comment]
The issue is that the version is being incremented only on the root document.  I still need to understand what the correct thing to do w/ sub-documents are.

**Comment by murphysj** [comment]
Will this be an issue for CIM2? Will we ever be editing multiple documents at once since most sub-documents (e.g. citation from a model component) will be linked by reference.

**Comment by allynt** [comment]
I suspect you are correct, but would like to confirm w/ the rest of ES-DOC before closing this ticket.

**Comment by allynt** [comment]
This is no longer an issue for CIM2.
