### ISSUE TITLE
Subform save button hard to find.

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#152]
WHO: Sylvia

Noticed when Cecelia was trying to customize that she frequently did not see the "save" button because she had to scroll to find it. We should look into making the window larger or having the subform become the page, vice a popup. Not sure what would be better.

**Comment by allynt** [comment]
The button is in a standard place.  The issue w/ scrolling is related to #407.  I am closing this issue in favour of that one.
