### ISSUE TITLE
Add text indicating what browsers we support. 

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#176]
WHO: Galia

It is not obvious that IE does not work for all users. Add documentation someplace indicating this.

**Comment by allynt** [comment]
In fact, there are issues w/ all non-Firefox browsers (see #215).

**Comment by murphysj** [comment]
#215 is fixed, but if we don't test on IE, then we should just say chrome and FF etc. On CoG we have this on the login page. Not sure where it should be for the Questionnaire.

**Comment by allynt** [comment]
Demonstrated to Sylvia on 25 November 2015.
