### ISSUE TITLE
Optimize Customizer Form by only loading content as needed

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#183]
WHO: Allyn

**Comment by rsdunlapiv** [comment]
I would like to +1 this as an important priority.  When using the customizer in Chrome, I am often prompted if I want to wait for the script to finish or cancel it.

**Comment by allynt** [comment]
There are 3 main parts to this:

1) get caching of customizations working [DONE]
2) get loading of form sections working
3) ensure that unloaded forms still have data (such as when activating/deactivating a vocabulary) passed to them

**Comment by allynt** [comment]
This is working, except for when a category customization has been deleted.  That features has been ticketed.

**Comment by allynt** [comment]
Works for the main customization but not for subform customizations yet.

**Comment by allynt** [comment]
Demonstrated to Sylvia on 06 May 2015.
