### ISSUE TITLE
CodeAccess in the Editor should be a larger text box

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#201]
WHO: Sylvia

This may be up to a paragraph.

**Comment by allynt** [comment]
This can be customized to render as a "Text Field" instead of the default "Character Field."

**Comment by murphysj** [comment]
THen we may need some description on the difference between these.

**Comment by allynt** [comment]
The field label says: "How should this field be rendered?"
The help text says: "By default, all fields are rendered as strings. However, a field can be customized to accept longer snippets of text, dates, email addresses, etc."
The choices include: "Character Field (default)" and "Text Field (large block of text as opposed to a small string)"

**Comment by murphysj** [comment]
You mean I had to READ the help text??? Geeesh!

Ok, close this.

On Wed, Jan 7, 2015 at 2:04 PM, allynt <notifications@github.com> wrote:

> The field label says: "How should this field be rendered?"
> The help text says: "By default, all fields are rendered as strings.
> However, a field can be customized to accept longer snippets of text,
> dates, email addresses, etc."
> The choices include: "Character Field (default)" and "Text Field (large
> block of text as opposed to a small string)"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/201#issuecomment-69091665>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753
