### ISSUE TITLE
Responsible Party selection box too small in the Editor

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#216]
WHO: Sylvia

You can't see the rest of the RP to select one from the previous list. See attached. 

![responsible_party](https://cloud.githubusercontent.com/assets/1512704/6083427/a80c6418-ade5-11e4-84b7-ba0dfb1a871e.png)

**Comment by allynt** [comment]
This can be done in conjunction w/ #164.

**Comment by murphysj** [comment]
we are getting rid of this selection all together.

**Comment by allynt** [comment]
References are handled slightly differently now.  A separate dialog box is presented allowing users to select from published documents.  The full details of those documents can be seen in the dialog box.  I am therefore closing this ticket.  Hooray.
