### ISSUE TITLE
Make sure that relationship properties from separate instances don't unintentially point to the same models.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#217]
WHO: ESPS

Somehow, the "citation" property for both the CAM & POP models of ESPS wound up pointing to the same instance.  Ensure that this does not happen w/out the author understanding the consequences.

**Comment by allynt** [comment]
This needs to be double-checked, but I am guessing that it happend when an auther clicked "add" to create a new subform and then rather than selecting "create a new instance", selected one of the existing instances.  That is fine, but one of 2 things should happen at that point:

1) a further warning or something ought to appear explaining the repurcussions of pointing to the same instance.
2) a new instance which is a _copy_ of the existing instance should be used (again, documentation ought to appear explaining this).

**Comment by murphysj** [comment]
I did this when I used the "add" button to pull an existing citation from the DB. 

I thought one of the goals was to share both Citations and Responsible Parties across a project. 

So I am not sure why this was a problem.

**Comment by allynt** [comment]
It is a problem b/c it is unintuitive to users that editing a subform in one instance would result in changes to a corresponding subform in another instance.  If we do want to support this behavior, I need to make it very clear to users that that is what will happen.

**Comment by allynt** [comment]
Fixing this properly will require thinking through all the possible use-cases.  As a start, here are some thoughts:

* the issue is "copy by reference" (CPR) vs. "copy by value" (CPV)
* we should be able to support both
* implicitly, CPR should be handled by *not* using a subform & CPV should be handled by using a subform
* the current problem w/ not using a subform is that there is no way to create an inital entry in the db for the thing being referenced
* this can be solved the same way that the Django Admin does it, w/ an "add new" button which brings up another Editor
* in the meantime, we should have some extra documentation telling users to be careful when editing subforms b/c those changes will propagate to other users
* we should have a policy of always using subforms (but automating this is really hard, so I don't mind just forcing users to be pendantic when creating customizations)
* is the distinction between subforms and not subforms enough, or does there need to be some other way (icons? colors?) to indicate a "shared" instance?  (This question is another way of asking, would we ever use subforms in a CBR scenario?)

**Comment by allynt** [comment]
This is no longer an issue.  Where the relationship points to another CIM document, a "reference" is used which just points to some external location.  Where the relationship points to some internal CIM structure, a local copy is _always_ used.  Thus two properties cannot point to the same thing.
