### ISSUE TITLE
Change message upon publication

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#218]
WHO: Cecelia

Change the message that pops up when publishing to say

"Successfully saved and published" instead of just "saved".

**Comment by allynt** [comment]
This is a short-term fix.  In the long-term, I was thinking of relegating the publish functionality to the project index page as part of the redesign.

**Comment by allynt** [comment]
The message should say saved & published instance(s).  (Notice the "(s)".)

**Comment by allynt** [comment]
Demonstrated to Sylvia on 19 Feb 2015.
