### ISSUE TITLE
Create table of all projects on the home page just for super admins

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#222]
WHO: Sylvia

In manual testing for 1.12.0.0, the test says "main index has current set of active projects".

How would you know looking at this list if all the active projects are included? 
How would you know how many inactive project there are?
What does active mean? 

I would suggest a table that displays below the pull down that only renders if the user has super-staff status. It might display the following

Project | Creation Date | Project Owner | Last Accessed | Status 

I don't know the project object and what can be pulled. 

and any other metrics deemed worthy.

**Comment by allynt** [comment]
I don't think this is a good idea.  I don't want to expose inactive projects to anybody other than the site administrator.  To check that the index page only displays active projects, just requires a functional_test that I could write.

**Comment by murphysj** [comment]
To me the super admin is the site administrator.

On Wed, Aug 5, 2015 at 1:17 PM, allynt <notifications@github.com> wrote:

> I don't think this is a good idea. I don't want to expose inactive
> projects to anybody other than the site administrator. To check that the
> index page only displays active projects, just requires a functional_test
> that I could write.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/222#issuecomment-128115532>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
This can be handled in the Django Admin interface.  It is not worth the extra coding or confusion to add it to the main index page.
