### ISSUE TITLE
Redesign project index to improve the look-and-feel and to display differently to select roles.

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#223]
WHO: Sylvia

We have a lot of text on the page saying what you can and cannot do. No one will read that. 

The better solution is to render the page according to user role: super admin, project admin, project member, unauthenticated user. 

We do this in cog using the following type of filter:

   {% if request.user.is_staff %}
     * give them the world
   {% else %}
     * make them pay for everything
   {% endif %}

Talk to me before starting this ticket.

**Comment by allynt** [comment]
Here is a pretty picture.
![project_index](https://cloud.githubusercontent.com/assets/1542786/6180292/0a46e41a-b2e0-11e4-9058-1c3940331bc3.png)

**Comment by allynt** [comment]
This looks pretty awesome: https://django-tables2.readthedocs.org/en/latest/.  Is it worth adding another dependency?

**Comment by murphysj** [comment]
Note sure. There is only one small example on the page. We would have to
discuss what you thinks it buys us in terms of look and feel versus time to
implement. I don't think dependencies are a big deal unless they become
deprecated.

On Wed, Feb 18, 2015 at 6:38 AM, allynt <notifications@github.com> wrote:

> This looks pretty awesome:
> https://django-tables2.readthedocs.org/en/latest/. Is it worth adding
> another dependency?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/223#issuecomment-74864650>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
dd2840c3daa39dcf1813ef6f152f352d46948b3f layed the initial groundwork for the Project Page redesign.

The following tickets are being subsumed into this one:

* #238 - indicate which customizations are default


Still need to:

**Comment by allynt** [comment]
Still todo:

* make the tables 100% width (so that the "odd"/"even" colors go to the end of the fieldset.

**Comment by allynt** [comment]
Demonstrated to Galia on 11 March 2015.

**Comment by allynt** [comment]
Demonstrated to Syvia on 12 March 2015.
