### ISSUE TITLE
Be able to delete a customization

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#224]
WHO: @murphysj, @rsdunlapiv 
Not sure where or how? 

Perhaps a delete button on the form itself? A new pull down?

**Comment by allynt** [comment]
This can be incorporated into the redesign of the index page (#223)

**Comment by allynt** [comment]
This must only apply to non-default customizations.

**Comment by allynt** [comment]
This must cascade, not only to property customizations but relationship model customizations.

**Comment by allynt** [comment]
This has been done, but the functionality is only currently available to the site admin.

**Comment by allynt** [comment]
Demonstrated to Sylvia on 16 June 2015.
