### ISSUE TITLE
Don't enable CVs by default in the Customizer

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#227]
WHO: Sylvia

This effects testing more than anything. 

It is nice to start down the list of things to do, which is slowly enable things. Having the CVs all selected by default means they have to be disabled from the start.

Whether a user will want them all enabled is a question though. I can see where having them off, particularly if they are doing a bunch of them, and then enabling them one at a time. I can also see not wanting to think about enabling them.

Any user feedback there?

**Comment by allynt** [comment]
This is no longer relevant since the customization optimization speeds up customizer form loading.
