### ISSUE TITLE
Don't change property accordion color on hover in the Customizer (open properties only)

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#228]
WHO: Sylvia

When a property is open, it becomes a light teal. If you hover over it, it becomes a dark teal and you can no longer read the text.

Remove the color change. If the color change serves some purpose, then change the text color etc so it can be read.

**Comment by allynt** [comment]
The color change shows that it is a clickable item.  The accordion header should respond to hovering just the same as when it is closed.

**Comment by murphysj** [comment]
Then we just need to make it legible when the color changes.

On Thu, Feb 12, 2015 at 12:23 PM, allynt <notifications@github.com> wrote:

> The color change shows that it is a clickable item. The accordion header
> should respond to hovering just the same as when it is closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/228#issuecomment-74134625>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
Changing the border rather than the background color.  This is the same look-and-feel as closed accordion headers.

**Comment by allynt** [comment]
Demonstrated to Rocky & Sylvia on 18 Feb 2015.
