### ISSUE TITLE
Pull down listing category options starts with deleted category

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#230]
WHO: Sylvia

In testing 0.12.0.0, I deleted a category in the customizer scientific properties. 
I then created a new category and was going to assign it. 
When I opened up the property accordion, which correctly shows no category listed, the category pull down defaults to the previously deleted name. 

It should only show names of available categories.

![new_category](https://cloud.githubusercontent.com/assets/1512704/6176407/f44a67fa-b2bb-11e4-9eca-4d924ecfc0e7.png)

**Comment by murphysj** [comment]
after saving, this pull down looks totally different.

a) all deleted categories are present (should there only be existing categories?)
b) the new category does not exist in the select area at all. 

![new_category_after_save](https://cloud.githubusercontent.com/assets/1512704/6176642/ba0d1db0-b2bd-11e4-985d-e82be02c9434.png)

**Comment by allynt** [comment]
This is related to #231 & #233.

**Comment by allynt** [comment]
As part of a general scientific category customization cleanup, what has to happen is:

1) when you remove a scientific category customization via the tagging widget, 
1a) the set of entries in the JSON "pending_deletion" variable should be updated
1b) the corresponding option for the category field of all scientific properties should be removed
1c) that should trigger a change to the enumeration_widget
1d) and should trigger a change to the category_name in the accordion header
2) property forms must have a category to validate (meaning if you don't re-set the category of a property that used to belong to the deleted category, you won't be able to save the customization_set)

**Comment by allynt** [comment]
Demonstrated to Sylvia on 5 May 2015.
