### ISSUE TITLE
New categories display outside of select pulldown and therefore unselectable

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#231]
WHO: Sylvia

In testing 0.12.0.0, I created a new scientific property category. I then tried to assign a property w/o a category to the new category. 

The new category does show up in the category section of the form, but it is outside of the select pull down (is there a reason these are radio buttons inside a pulldown?), so it can not be selected. 

![new_category](https://cloud.githubusercontent.com/assets/1512704/6176397/e69ce510-b2bb-11e4-8793-96e0546f457f.png)

**Comment by allynt** [comment]
This is related to #230 & #233.

**Comment by allynt** [comment]
As part of a general scientific category customization cleanup, what has to happen is:

1) when you remove a scientific category customization via the tagging widget, 
1a) the set of entries in the JSON "pending_deletion" variable should be updated
1b) the corresponding option for the category field of all scientific properties should be removed
1c) that should trigger a change to the enumeration_widget
1d) and should trigger a change to the category_name in the accordion header
2) property forms must have a category to validate (meaning if you don't re-set the category of a property that used to belong to the deleted category, you won't be able to save the customization_set)

**Comment by allynt** [comment]
Demonstrated to Sylvia on 5 May 2015.
