### ISSUE TITLE
Can't save customization after deleting a scientific property category

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#233]
WHO:  Sylvia

Found in 0.12.0.0 testing.

I created a brand new customization and made sure it saved with a good name and CV attached.

I then chose one tab of scientific properties

I then deleted one of the categories and tried to save. Got the attached YSD. 

![ysd](https://cloud.githubusercontent.com/assets/1512704/6177788/9ac0de3e-b2c6-11e4-9571-34033aff4ce9.png)

**Comment by allynt** [comment]
This is related to #230 & #231.

**Comment by allynt** [comment]
As part of a general scientific category customization cleanup, what has to happen is:

1) when you remove a scientific category customization via the tagging widget, 
1a) the set of entries in the JSON "pending_deletion" variable should be updated
1b) the corresponding option for the category field of all scientific properties should be removed
1c) that should trigger a change to the enumeration_widget
1d) and should trigger a change to the category_name in the accordion header
2) property forms must have a category to validate (meaning if you don't re-set the category of a property that used to belong to the deleted category, you won't be able to save the customization_set)

**Comment by murphysj** [comment]
Was not able to reproduce this in the latest testing of 0.12.0.0

**Comment by allynt** [comment]
This is related to #379.

**Comment by allynt** [comment]
No longer applicable b/c you can no longer delete scientific categories.
