### ISSUE TITLE
Prevent the same CIM metadata categorization from being applied to more than one ontology (CIM version).

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#236]
In theory, I ought to be able to re-use CIM Metadata categorizations (e.g. basic properties, document properties etc).  In practice, this is more trouble than it's worth (b/c I want to keep categories for different versions distinct).  So, rewrite the code to use a unique 1-to-1 relationship between categorizations and versions.

**Comment by murphysj** [comment]
It would be better if this categorization occurred in the CIM version not in the questionnaire.

**Comment by allynt** [comment]
Categorizations are not used in CIM2.
