### ISSUE TITLE
Append the word "(default)" after the default customization in the pull down

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#238]
WHO: Sylvia

In the laundry list of customizations, which can get long when testing, it would be good to rapidly find the default customization to a) potentially remove the default, or b) use it for further tests since it is the only one that has a View button.

Appending the word default, in () next to the name in the pull down would enable this to be found easier.

**Comment by allynt** [comment]
This can be done as part of the redesign of the project index pages, #223.
