### ISSUE TITLE
Hide instead of not including properties that have been customized not to display.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#242]
Just hide instead of not including properties that have been customized not to display.  This will make the code much more straightforward and prevent the needless looping that occurs in functions like `get_active_properties_and_categories`.  With the load-on-demand paradigm the extra template rendering should not be an issue.

**Comment by murphysj** [comment]
This is all related to #338.

**Comment by allynt** [comment]
When exporting a document, only those properties customized to be displayed should be serialized.

**Comment by murphysj** [comment]
Currently, we delete the item from the database. 

The cusp of this ticket is to remove the function call mentioned above that determines what has been displayed.

**Comment by allynt** [comment]
This is no longer an issue since moving to JSON / Angular.
