### ISSUE TITLE
Deeply nested properties do not propagate errors up to parent elements

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#25]
WHO: Galia

Although the questionnaire catches errors in deeply nested properties (ie: properties that are rendered w/in a subform), and correctly styles them, that style is not then applied to all of that property's parent containers (fieldsets, accordions, tabs, and component tree item) as it is with non deeply-nested properties.

**Comment by murphysj** [comment]
@allynt 

on the 2104 spreadsheet, this was listed as implemented. Is it?

**Comment by allynt** [comment]
This is implemented.  (But in the current state of things, you cannot get an error in a property since incomplete documents are allowed to be saved.  This will be changed once #300 is complete.)
