### ISSUE TITLE
Use the label property name in the ATOM feed rather than the generic term "name."

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#253]
The generic term "name" is used as the label.

A CIM Model can have a particular standard property designated as "the-one-to-use-to-refer-to-the-model." For ModelComponents, that happens to be shortName. It could potentially be any top-level property.

Are we okay w/ using the generic term "name," or should we use the actual property name so that the label would be "shortName" or "longName" or whatever?

**Comment by murphysj** [comment]
If we get away from an atom feed this may be no longer applicable.

**Comment by allynt** [comment]
Obviously, this relies upon #441.

**Comment by allynt** [comment]
This is not as straightforward as it seems; a model's label may be comprised of multiple properties.  So they way to do this is to have the feed use the term "label" instead of "name" and then to display its label.

**Comment by allynt** [comment]
Done in b5b23543219b8c868b20e54fc475612c15fa75bb.
