### ISSUE TITLE
Change how enumerations that use the "OTHER" are serialized.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#254]
WHO: @rsdunlapiv 

Currently, they are serialized like this:

`<value>OTHER: my other value</value>`

Consider doing something like this:

`<value other="true">my other value</value>`

**Comment by murphysj** [comment]
We care cuz currently in the tools, the OTHER: my other value is displayed.

**Comment by allynt** [comment]
Serializing to JSON instead of XML.
