### ISSUE TITLE
Change the term "default" to refer to which customization is used.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#264]
WHO: @rsdunlapiv 

Consider changing the term "default" to refer to which customization is used.  Rocky suggested "active."

**Comment by murphysj** [comment]
Perhaps "active" would work???

**Comment by allynt** [comment]
The name "default" is good enough.  Hardly anybody uses customizations anyway (especially since they are created automatically as of v0.16.0).
