### ISSUE TITLE
Saving scientific property enumerations does not work consistently?

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#266]
WHO: Galia

Saving scientific property enumerations does not work consistently?  Galia found once that setting the "ClassificationType" property in "StatisticalDownscaling_KeyProperties" and then saving it, did not save that property's data.  However, neither she nor I are able to replicate this.

**Comment by murphysj** [comment]
Allyn could not reproduce.

**Comment by allynt** [comment]
Allyn could not reproduce this.
