### ISSUE TITLE
Should updating a document based on a change from a customizer should be a manual, rather than automatic process?

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#278]
WHO: Galia

Updating a document based on a change from a customizer should be a manual, rather than automatic process.  See #210.  (Although this may be redundant b/c of #242.)

**Comment by allynt** [comment]
This is related to #338.

**Comment by murphysj** [comment]
on 8/11/15 with Cecelia and Rocky we decided this would be manual. The document would be flagged as out of sync on the project page.

**Comment by allynt** [comment]
Allyn concurs.
