### ISSUE TITLE
Change error message on bad login

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#284]
WHO: Sylvia

Login error message says:

"Please enter a correct username and password. Note that both fields may be case-sensitive."

Are they or are they not case sensitive? Be definitive.

**Comment by allynt** [comment]
ee08cd5dfd7665353a7cccf0440227a580b4757e addresses this.  It wasn't completely straightforward, b/c this uses the built-in Django authentication form.  Overriding the __init__ fn did the trick.

**Comment by allynt** [comment]
Demonstrated to Sylvia on 5 May 2015.
