### ISSUE TITLE
Indicate somehow that a "project join" is pending.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#287]
WHO: @rsdunlapiv 

Indicate somehow that a "project join" is pending.

**Comment by murphysj** [comment]
Rocky suggest greying out the button.

**Comment by murphysj** [comment]
In CoG we have a message box indicating the the project join was received and that the project owner has been notified etc.

**Comment by murphysj** [comment]
Has email notifications been set up for the questionnaire?

**Comment by allynt** [comment]
No.  And it shouldn't before #321.

**Comment by allynt** [comment]
WRT indicating that the project join was received, the Q does have that functionality.  I thought that Rocky was suggesting that the look-and-feel of the (join button on the) Project Page changes based on whether or not the user has requested to join the project.

**Comment by murphysj** [comment]
He was, but he was telling us what to do, so I rewrote it as what was
needed. Then we will figure out the best way to achieve it.

On Wed, Aug 5, 2015 at 9:13 AM, allynt <notifications@github.com> wrote:

> WRT indicating that the project join was received, the Q does have that
> functionality. I thought that Rocky was suggesting that the look-and-feel
> of the (join button on the) Project Page changes based on whether or not
> the user has requested to join the project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/287#issuecomment-128032596>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
Demonstrated to Sylvia on 25 November 2015.
