### ISSUE TITLE
deselect "Can the value of this property be edited?" causes Editor to fail

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#295]
WHO: Sylvia

In testing 0.12.0.0

I deselected "Can the value of this property be edited?" in the customizer and saved it. 

I clicked "view in Editor" 

The Editor does not render correctly

![editiable](https://cloud.githubusercontent.com/assets/1512704/6628944/8ba7a47c-c8cf-11e4-8bfd-6f2f90d75725.png)

**Comment by allynt** [comment]
Demonstrated to Sylvia on 5 May 2015.
