### ISSUE TITLE
Add categories to subforms for complex relationship fields. 

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#308]
WHO: @murphysj 

> Whether or not a CIM class's standard properties have categories is a function of the "categorization" for that CIM version.  In general, classes that are also document types (like modelComponent, experiment, etc.) have categories while those that are not (responsibleParty, citation) do not.  This is why the subform customization do not consistently have categories. 
> 
> Having said that, I'm not sure what the correct behavior is.  Thus far, subforms should not have categories, because they have not been document types.  However, very soon we will begin to have document types w/ standard properties that are document types.  In that case, it might make sense to keep them.
> I vote for ticketing this and coming back to it when there are some better fleshed-out use cases for having categories.
> 
> Regards,
> Allyn
> 
> > Hi Allyn,
> > 
> > Testing subform customization.
> > 
> > Almost all of the properties in the subforms have no category.
> > 
> > Some subforms list Available categories (document properties, basic properties, component properties), like they would for a single standard property. But the the attributes themselves have no categories and no way to assign them.
> > 
> > This is confusing.
> > 
> > Should subforms have categories at all?
> > 
> > Sylvia

**Comment by allynt** [comment]
If subforms are no longer used for models of sufficient complexity that would require categories (like, grids, platforms, etc.; things that can exist as documents in their own right), then this ticket becomes irrelevant.

**Comment by murphysj** [comment]
CIM 2.0 is leaning towards all separate classes being their own documents.

**Comment by allynt** [comment]
In addition to CIM2 treating most separate classes as documents, the use of categories has now been normalized such that all properties have a category (in the event that there is no explicit category defined in the CIM the "uncategorized category" is used which by default does not appear in the editor form) and categories can be rendered wiithin subforms.

Therefore, this ticket is no longer valid.
