### ISSUE TITLE
Be able to display and export "numerical experiment" document type

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#31]
WHO: ES-DOC, downscaling-metadata

Currently the questionnaire can support statisticalmodelcomponents and modelcomponents. In theory, the infrastructure exists to support the full set of CIM document types.

**Comment by murphysj** [comment]
This goes hand in hand with #53. One is ingestion the other is exportation.

**Comment by murphysj** [comment]
Bryan indicated that experiment documents were going to be generated via his notebook. so this is letter priority.

**Comment by allynt** [comment]
As of v0.17.0, the Q can deal w/ all CIM2 document types.
