### ISSUE TITLE
Restrict the creation of documents to only those document types for which there exist a default customization

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#316]
WHO: NCPP

On the Project Pages, restrict the creation of documents to only those document types for which there exist a default customization.

**Comment by murphysj** [comment]
Seems like we should also allow a "what the CIM" wants customization. NCPP is no longer around.

**Comment by allynt** [comment]
This is sort-of-done.  The project page restricts the creation of documents to those that exist in the ontologies associated with that project.  And if a corresponding customization does not exist, then a suitable error message is shown.  I think that this is better than disabling document types with no default customization b/c it wouldn't necessarily be clear _why_ they were disabled.
