### ISSUE TITLE
Require users to provide an email address upon registration. 

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#321]
Require users to provide an email address so that there is a way for the site & project administrators to communicate with them.

**Comment by murphysj** [comment]
Need to find out if this is needed for cmip6

**Comment by allynt** [comment]
This is required in general b/c there are some messages (like joining/leaving a project) that get emailed to a user.

**Comment by allynt** [comment]
Since moving to "django-auth" an email address is required.  However, I still need to validate that address.  This is covered in #535.
