### ISSUE TITLE
Sometimes the Editor fails to load

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#322]
WHO: @murphysj 

Sometimes when I click on a component (I am paying with Model Coupling Metadata) I will get the loading button that goes ON forever and then nothing happens. I can't tell if it failed to load or if the component itself is empty (can't image that use case). May have a load bug here plus we need some sort of failed to load error message.

**Comment by murphysj** [comment]
Allyn was not able to reproduce. May not be an issue.

**Comment by allynt** [comment]
Could not reproduce.  This may have happened when there was a server error on the AJAX call.  However, since v0.16.0 I use a progress bar rather than a modal loading popup box, so this issue should not reoccur.
