### ISSUE TITLE
Enable the Questionaire to handle contraints

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#323]
WHO: ES-FDL

The two main things that came up are (1) constraints and (2) conditional navigation.

In the case of (1), sometimes an answer to a question reduces the number of possible responses to follow on questions. Or, sometimes certain combinations of answers do not make sense.  I could probably come up with specific examples of these from ES-FDL if you require them, but let's only do this if we have prioritized it.

For (2), if you answer "no" to certain questions, then you night want to skip a whole section, or turn off a tab, etc.  Google Forms has a basic capability like this.  We currently have no concept of "flow" through the questionnaire, so I suspect that this would be a major change.  Again, it would have to be prioritized and an assessment of the actual development effort required.

**Comment by murphysj** [comment]
a) We may be getting away from constraints in the CIM
b) The constraints in the CMIP5 questionnaire were output in such a way as to me unusable in any follow on tools.
c) Any constraints would have to be in the CV.

**Comment by murphysj** [comment]
Rocky can provide specific details if we every consider doing this.

**Comment by allynt** [comment]
CIM2 is not interested in doing this.
