### ISSUE TITLE
Add ability to customize scientific properties as one page vice in tabs

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#324]
WHO: @rsdunlapiv 

One final thought, just from me, is whether the new editor allows the same amount of content per screen as the old questionnaire.  There are a lot of tabs and accordions requiring a lot of clicks and each question takes up a lot of real estate.  It seems to me like the CMIP5 questionnaire was more dense.  There is something psychological about the total number of pages/tabs that I need to access and respond to, even if its the same content as a long page where I have to scroll.

**Comment by allynt** [comment]
If this is a complaint about the customizer, I don't care b/c hardly anybody will use the customizer and you can already filter properties by category.

If this is a complaint about the editor, then you could already force this behavior by customizing categories not to appear but properties to still appear.
