### ISSUE TITLE
What should happen when opening an existing document with property values that have since been customized not to be included in the set of enumeration options?

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#338]
What should happen when opening an existing document with property values that have since been customized not to be included in the set of enumeration options?

**Comment by allynt** [comment]
This sort of change will not effect publications.

Don't show the un-displayed field in the editor.

**Comment by allynt** [comment]
Allyn suggested adding a flag to the document indicating that it's "out of synch" with the default customization prompting users to re-edit it.

Sylvia thinks that is too complex and the onus should be on the project administrator to not do stupid things after the fact in the customizer.

**Comment by murphysj** [comment]
Answer decided on the 8/11/15 ES-DOC ticket review with Cecelia and Rocky that:

a) We want a flag that indicates that the document is out sync (on the project page)
b) Project administrator is expected to fixe it manually.

**Comment by allynt** [comment]
Allyn concurs; this is documented in #396.
