### ISSUE TITLE
Category customization keys are not immutable.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#378]
Ensure that a category customization's key is immutable.  A category customization's key starts off being a copy of the category proxy's key.  However, if a user changes the name of that category customization, then the key gets reset.  During the publication process, the proxy is retrieved using the customization key.  Obviously if these don't match up, then an error will ocurr.

**Comment by allynt** [comment]
This was responsible for the ES-FDL project's published documents having empty subcomponent content.

**Comment by allynt** [comment]
3bc1d7a7e66ab8fed9ed5cfd321521905a607fe7 fixes the db if this situation has already occurred.

**Comment by murphysj** [comment]
#379 does not effect this because standard properties still have names and we are not deleting or adding.

**Comment by allynt** [comment]
Explained to Sylvia on 25 November 2015.
