### ISSUE TITLE
Disable the ability to add/delete scientific categories in the Customizer

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#379]
Disable the ability to add/delete scientific category customizations.  I don't think users actually use this.

**Comment by murphysj** [comment]
Currently we can add new SP categories. This really changes the CV intent.

**Comment by murphysj** [comment]
This makes more sense for CIM 2.0, which gets rid of external CVs and SPs all together. SPs, are just another standard property.

**Comment by allynt** [comment]
Completing this ticket will satisfy #333, #332, #330, #329, #271

**Comment by allynt** [comment]
Demonstrated to Sylvia on 25 November 2015.
