### ISSUE TITLE
Be able to display an export the CIM2 conformance document

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#387]
WHO: Bryan

The questionnaire will be used to collect model component information for CMIP6. 

Bryan has suggested that it will also be used to collect conformance information. 

As yet we don't know the structure of this document since it is still in development.

**Comment by allynt** [comment]
Individual document types are not handled differently in the Q.  It is an autogenerated form that just works regardless of the ontology contents.  Therefore, a separate ticket for the "conformance" document type is not needed.
