### ISSUE TITLE
Determine if any branding (or other visual appearance) is needed to satisfy CMIP6.

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#392]
WHO: Cecelia

Contact Bryan.

**Comment by allynt** [comment]
FWIW, as of v0.15.0.0, there is code to support associating an image w/ a particular project.  There is not yet any code that renders that image in a template.

**Comment by murphysj** [comment]
At some point Eric said no. I suspect that may change. Moving this to 1.0 since it is cosmetic in nature.

**Comment by allynt** [comment]
ES-DOC has confirmed that no branding is needed.  

However, as mentioned above, the code to insert logos on a per-project basis already exists.
