### ISSUE TITLE
Create an initial Questionnaire User's Manual

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#40]
WHO: Sylvia

ES-DOC is going to need to document all its tools. Those are covered in separate tickets. We need a user's manual for the Questionnaire as part of this.

**Comment by allynt** [comment]
This has been done (although it is expected that the content will continue to be updated).

It can be seen both at https://es-doc.org/tools/ and https://earthsystemcog.org/projects/es-doc-models/questionnaire/help
