### ISSUE TITLE
Separate the "name and version" column in the project page into two separate columns.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#435]
WHO: @murphysj 

Separate the "name and version" column in the project page into two separate columns: "name" and "column."

**Comment by allynt** [comment]
This has been done.  I have not implemented sorting by version, though.

**Comment by murphysj** [comment]
Agree, sorting by version should not be required.

On Fri, Jan 8, 2016 at 9:22 AM, allynt <notifications@github.com> wrote:

> This has been done. I have not implemented sorting by version, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ES-DOC/esdoc-questionnaire/issues/435#issuecomment-170046001>
> .
>



-- 
******************************************
Sylvia Murphy
NESII/CIRES/NOAA Earth System Research Laboratory
325 Broadway, Boulder CO 80305
Time Zone: U.S. Mountain
Web: http://www.esrl.noaa.gov/nesii/
Email: sylvia.murphy@noaa.gov
Phone: 303-497-7753

**Comment by allynt** [comment]
Demonstrated to Sylvia on 15 January 2016.
