### ISSUE TITLE
Questionnaire can generate CIM2 simple documents

### ISSUE THREAD

**Issue by momipsl** [ES-DOC/esdoc-questionnaire#466]
_From @murphysj on August 12, 2016 17:14_

e.g. citation

depends on cim2 being finalized for this document.

_Copied from original issue: ES-DOC/esdoc-docs#195_

**Comment by murphysj** [comment]
We have proved this for citations, so I think we can close this with 0.16.0.0. there will be follow-on tickets to be able to generate other simple documents besides citations.
