### ISSUE TITLE
Add "forgot password" & "forgot login" functionality to Questionnaire.

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#500]
WHO: @ceblanton 

Add "forgot password" functionality to Questionnaire.

**Comment by ceblanton** [comment]
A related "forgot login" would be nice too, since the login and email are different

**Comment by allynt** [comment]
In the long-term, think about transitioning from separate login names to using email addresses.  (Cecelia always wanted email addresses to be required anyway.)

**Comment by allynt** [comment]
This has been done.  As per the comments, I ought to eventually make the login the email address.
