### ISSUE TITLE
Property accordion has be clicked twice in order to open (Customizer)

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#509]
WHO: Sylvia

In testing the customizer. Mac/FF.

Opening a property to choose options. On the first click, it "opens" but the content is not visible. 

Upon closing the accordion and clicking it again, the content is visible. 

Image is of partially visible accordion. 

![accordion](https://cloud.githubusercontent.com/assets/1512704/19534014/54f2316e-95ff-11e6-9ebd-a2441359f98c.png)

**Comment by allynt** [comment]
This has something to do w/ the interaction of my open-an-accordion-item code and my sort-an-accordion-item code.

**Comment by allynt** [comment]
This was fixed as a side-effect of c439b7a3faed126d67fe25b743c7be8671f016b4 for #518.
