### ISSUE TITLE
Adjust message upon saving an instance (Editor)

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#510]
WHO: Sylvia

The current message said something like "...model successfully saved". Here I presume you mean model in the django sense. 

later i saved again and the message was different, so we need to look at this carefully.

**Comment by allynt** [comment]
This is indeed an error.  When you save a new instance, the message is:

"Successfully saved model (version x.y)."

When you save an existing instance, the message is:

"Successfully saved document."

Which do you prefer?

**Comment by allynt** [comment]
Actually, this uncovered a more serious issue:

When a new model (either a customization or a realization) is saved, I add a success message to Django's messaging queue which gets rendered when the page is reloaded after submission.  When an existing model is saved, I do the same thing but the page is never reloaded.  

So I was manually rendering a success message in JavaScript.  But this meant that the _next_ time a page was loaded, that pending message got displayed.

c55d9e6474a418711679d19567a8dcc3b2aab55a and 5d1df81c83a6a368249c054abe90705909dd6552 sort this out by making an AJAX call to the server to check for messages after any model is saved.

**Comment by allynt** [comment]
@murphysj  - the message can still be changed, though.

**Comment by murphysj** [comment]
Lets make it simple and go with "Successfully saved document."
It is universal and I don't think anyone is going to read a complex message anyway.

**Comment by murphysj** [comment]
This issues emphases that you really must be constantly testing the interface like a real human would. I noticed this right away after a minute or so. 

When you test for the release, how much human testing do you do?
