### ISSUE TITLE
When browser made smaller, is nillable box wraps while main entries stay the same

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#517]
who: sylvia

will just want to examine the spacing of the editor as the browser is made smaller. I suspect we will want the main entry boxes to shrink a bit as well or nothing shrinks and we keep a fixed width. 
![editor_ie](https://cloud.githubusercontent.com/assets/1512704/19579659/05b2722c-96df-11e6-967f-73604c003217.png)

**Comment by allynt** [comment]
One solution (the easier solution) is to just have a fixed width for the parent div.

**Comment by allynt** [comment]
This is a symptom of #516.  Closing as duplicate.
