### ISSUE TITLE
Be able to import and edit an existing "numerical experiment" document

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#53]
WHO: ES-DOC, SPECS

This will be the first document to try and ingest. SPECS wishes to create experiment documents. For CMIP5, however, these were created outside of the Metafor Questionnaire and exist as standalone (as I recall, non-CIM compliant) documents.

**Comment by allynt** [comment]
As a first step, verify that CMIP5 Numerical Experiment documents are CIM-compliant.

**Comment by murphysj** [comment]
Bryan says hold off on CMIP5 ingest for now. They are going in a different direction.

**Comment by allynt** [comment]
As of v0.17.0, the import code will no longer be document-type specific.  Furthermore, there will be a mapping from CMIP5 (CIM1) to CMIP6 (CIM2) prior to importing.  So a more straightforward (possibly leveraging pyesdoc) CIM2 document import function is what is required.  This is covered in more detail by #468.
