### ISSUE TITLE
Be able in import and edit an existing "processor component" document

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#54]
WHO: CMIP6

Part of the overall ability to import and edit CMIP5 document sets.

**Comment by allynt** [comment]
As of v0.17.0, the import code will no longer be document-type specific.  Furthermore, there will be a mapping from CMIP5 (CIM1) to CMIP6 (CIM2) prior to importing.  So a more straightforward (possibly leveraging pyesdoc) CIM2 document import function is what is required.  This is covered in more detail by #468.
