### ISSUE TITLE
Be able to import and edit an existing "simulation run" and "simulation composite" document

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#55]
WHO: CMIP6

Part of the overall need to ingest a CMIP5 document set.

**Comment by allynt** [comment]
As of v0.17.0, the import code will no longer be document-type specific.  Furthermore, there will be a mapping from CMIP5 (CIM1) to CMIP6 (CIM2) prior to importing.  So a more straightforward (possibly leveraging pyesdoc) CIM2 document import function is what is required.  This is covered in more detail by #468.
