### ISSUE TITLE
Allow relationships to have multiple targets

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#61]
Add support for relationships to abstract classes by allowing relationships to have multiple targets.

Currently a standard relationship property points to some class.  The CIM, however, allows some relationships to point to abstract classes.  The intention is to allow that property to point to any of the concrete child classes of that abstract base class.

The Q needs to support this. For references (ie: relationships to standalone documents) it is simple. But for inline relationships (ie: relationships to standard CIM classes) it is much more complex.

Additionally, some way of allowing users to choose, and change, which (inline) concrete child class should be pointed to is required.

This is a "nice-to-have" feature of CIM1, but a requirement of CIM2.

**Comment by allynt** [comment]
I have found this in the "ensemble_members" property of the "multi_time_ensemble" class of CIM2.  

I am surprised I have not found it in experimental requirements.

I have asked the ES-DOC team whether or not this use of abstract relationship targets is expected a lot in CIM2;  If not, I can table this issue for now.

**Comment by allynt** [comment]
According to Bryan, multiple targets do not result only from a property that points to an abstract class; any class can have children.

**Comment by allynt** [comment]
Wrote some code to work out which classes in CIM2 have properties that point to multiple targets.  (The code to apply a fn recursively through an entire set of proxies was added in support of recursive classes #451: 016d490214ae6a3558418b6d2bd371902a933d05).  The result was:
```

['shared.reference',
 'activity.ensemble_axis',
 'designing.simulation_plan',
 'science.algorithm',
 'designing.forcing_constraint',
 'activity.parent_simulation',
 'data.related_data',
 'activity.uber_ensemble',
 'designing.numerical_requirement',
 'designing.project',
 'science.sub_process',
 'science.model',
 'designing.domain_properties',
 'shared.pid',
 'designing.output_temporal_requirement',
 'software.software_component',
 'designing.temporal_constraint',
 'activity.conformance',
 'activity.ensemble',
 'designing.numerical_experiment',
 'data.simulation',
 'activity.ensemble_member',
 'platform.machine',
 'platform.performance',
 'shared.citation',
 'designing.multi_time_ensemble',
 'shared.party',
 'data.downscaling',
 'platform.partition',
 'shared.vocab_member',
 'shared.doc_quality_review',
 'designing.ensemble_requirement',
 'science.process',
 'data.dataset',
 'designing.multi_ensemble',
 'platform.component_performance']
```
Since these _do_ include classes that the Q needs to support, I will _not_ be tabling this issue

**Comment by momipsl** [comment]
I will extend esdoc-mp to add a new sub_classes attribute to esdoc_mp.core.class_

**Comment by allynt** [comment]
I'm not sure that's needed.  I have tackled this by writing 2 fns:

`recurse_through_parent_classes(fn, cls, **kwargs)` which lets me apply `fn` to `cls` _and all its base classes_

and `def get_relationship_property_target_classes(property)` which uses `recurse_through_parent_classes` to check if the target of a particular property appears as the base class of any other classes in an ontology.
