### ISSUE TITLE
Add a warning when the System Administrator deletes a project's vocabulary, ontology, or categorizations using the Django interface

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#73]
Deleting these objects causes the associated proxies to be deleted.  

A warning box should to the process.

**Comment by murphysj** [comment]
This is related to #338, dealing with customization changes.

**Comment by allynt** [comment]
According to #396, re-registering will be restricted to patch releases.  Make sure that patch releases never delete content.

**Comment by murphysj** [comment]
We may not be able to do this since it is happening at the Django Interface level

**Comment by allynt** [comment]
This is no longer true - proxies are not associated w/ projects.  Deleting an ontology from a project with existing customizations or realizations is a bad idea, but it will not cause cascading deletions.  

(Having said this, modifying the ontologies absolutely needs to be handled and is covered via the synchronization code as implied above.)
