### ISSUE TITLE
Vocabularies list/toggle in the Customizer can't handle long names

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#81]
WHO: Sylvia

There is a new feature in the Customizer that lists all of the Controlled Vocabularies that can be customized. Users can toggle between them. 

This list is currently a vertical list on the left hand side of the property window. This is a narrow space any any Controlled Vocabulary name longer than "atmosphere" won't fit and can not be seen.

**Comment by allynt** [comment]
Done in a previous release.
