### ISSUE TITLE
Set default "text box" size in the Editor

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#82]
WHO: Sylvia

Text boxes in the Editor are too large vertically and too short horizontally. Choose a standardized size as a default.

**Comment by allynt** [comment]
Made it slightly narrower and taller than those in the Customizer.  Narrower so that it's the same size as the enumeration widgets.  Taller so that it shows more text.

**Comment by allynt** [comment]
Demonstrated to Rocky & Sylvia on 18 Feb 2015.
