### ISSUE TITLE
In the customizer, choosing to use a subform should immediately highlight the need to create that subform

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#91]
Although the error of trying to save a property customizer that uses a subform w/out having specified which subform to use is successfully caught, there is no indication to users that the next thing to do after selecting the "customize subform" checkbox is to click the "customize subform" button.

**Comment by murphysj** [comment]
For some reason I think this was done. If so close.

**Comment by allynt** [comment]
No longer applicable b/c of #402
