### ISSUE TITLE
Be able to convert CF or CSDMS standard_names to mindmaps

### ISSUE THREAD

**Issue by murphysj** [ES-DOC/esdoc-questionnaire#94]
WHO: Sylvia

If people want to use the CF or CSDMS standard names in the questionnaire, they will first have to be converted to a mindmap so that they can be ingested. 

What format they will have to be first converted to (e.g. flat text list) will have to be determined. 

What sort of script this will take will have to be determined.

**Comment by allynt** [comment]
No longer applicable.
