### ISSUE TITLE
Add the ability to customize the name of the scientific property tab

### ISSUE THREAD

**Issue by allynt** [ES-DOC/esdoc-questionnaire#97]

**Comment by murphysj** [comment]
If #379 is implemented, this will no longer be applicable.

**Comment by allynt** [comment]
That is not correct.  This is for customizing "scientific properties" to say something like "model properties", and has nothing to do with the categories w/in scientific properties.

**Comment by allynt** [comment]
No longer applicable b/c of changes to CIM2.
